### ISSUE TITLE
System Redirects to News Page When Attempting to Manage Shifts with No Existing Shifts but Defined Shift Types

### ISSUE THREAD

**Issue by Corborax** [eurofurence/crittersystem#13]
### User Role

Critter System Staff

### System Type

Computer

### Operating System

Other

### OS Version

-

### Steps to Reproduce

1. Define shift types in the system without creating any shifts.
2. Attempt to access the Shifts section.
3. Observe that the system redirects to the News page with an error message.
4. Note that creating shifts is only possible when logged in as an Admin.

### Expected Behavior

The Shifts section should display a message indicating that no shifts are currently available, and the user should be able to create new shifts if they have the appropriate permissions.

### Actual Behavior

Instead of displaying an empty shifts list or allowing shift creation, the system redirects to the News page with an error message. Shift creation is only possible when logged in as an Admin.

### Feature Area

Shift Creation and Management

### Severity

Major Issue

### Error Messages

(Include any error messages here if applicable. If none were provided, you could write "No specific error message provided.")

### Workarounds Tried

No workarounds available for non-admin users.

### Network Type

None

### Anything Else?

The issue was noticed by @Tarian-Wolf and seems to be affecting the ability to create shifts for non-admin users when no shifts have been created yet.I ne

**Comment by RustyBraze** [comment]
This one, I need to create a branch from the previous branch I created to fix another bug. Its the same file to correct the issue.

**Comment by RustyBraze** [comment]
@Corborax Can you please check if the solution implemented is ok?
If yes, I can close the ticket and then I can make a merge request (needs to be after the other bugfix I did, because it is the same file)

**Comment by Corborax** [comment]
Waiting for @Tarian-Wolf answer

**Comment by RustyBraze** [comment]
Nice, closing the topic after confirmation
