### ISSUE TITLE
Telegram handle not linked in All-Critter List

### ISSUE THREAD

**Issue by Corborax** [eurofurence/crittersystem#15]
### User Role

Critter System Staff

### System Type

Other

### Operating System

Other

### OS Version

-

### Browser Details (if applicable)

-

### Steps to Reproduce

1. Enter Telegram handle with @ in the User Info
2. Show All Users in the Critter System

### Expected Behavior

No @ in front of the Telegram handle
If I click a link it should link me to telegram / the actual person 

### Actual Behavior

If I click on a user with @ it leads to the telegram website and not the t.me/@user website

### Feature Area

Shift Creation and Management

### Severity

Minor Issue

### Workarounds Tried

copy the username without the @ and open the website manually

### Network Type

None

**Comment by Fenrikur** [comment]
The `@` will be automatically trimmed on save, so it being there is a legacy issue only present for users that set their handle before the change. (=
