### ISSUE TITLE
Critters can see staff internal shifts

### ISSUE THREAD

**Issue by Corborax** [eurofurence/crittersystem#23]
### User Role

Attendee (Critter)

### System Type

Other

### Operating System

Other

### Steps to Reproduce

1. Have an internal role for Staff 
![grafik](https://github.com/user-attachments/assets/ce976c1e-89ef-4b04-aa6a-b243e322b3ec)
2. If a Critter wants to join the join the group, they will be added as "uncomfirmed" 
![grafik](https://github.com/user-attachments/assets/616619d9-8340-46d4-a9ab-1ff6780bcac5)

### Expected Behavior

Shifts that are hidden can't be seen by members who are not confirmed members of this year.

### Actual Behavior

1. Being an uncomfirmed member of a critter type enables this Critter, still being uncomfirmed, to view internal Staff shifts from the Critty Type menu / Critty type details Shift tab
![grafik](https://github.com/user-attachments/assets/3b149ff2-f65b-4121-9a8f-e6f12e8bd189)
2.It also enables them to view the internal Staff shifts from the Shift overview
![grafik](https://github.com/user-attachments/assets/2b7b984a-f27d-4ec3-a3a6-f7af9edb052e)

### Feature Area

Volunteer Sign-Up

### Severity

Critical Problem

### Network Type

None

### Anything Else?

2 changes are required:
- Hide the unconfirmed crittertypes in the shift overview / list.
- Completely block/hide the shift tab within the critter type info if the option "Hide from shift view" is set.

**Comment by Balenty** [comment]
Alternatively, these changes could be done (2nd change is differnet):
1. In the shift search, you cannot filter your Crittetypes in which you are just unconfirmed (when this hide option is set).
2. The shift tab in the Crittertype Infopage is only available when you are a full member of this Crittertype (when this hide option is set).
