### ISSUE TITLE
Add TG Icon before handle or instead of mobile icon

### ISSUE THREAD

**Issue by rotpelz** [eurofurence/crittersystem#26]
### What problem are you trying to solve with this feature?

The @name doesn't indicate whether it's just the tool-intern handle or something else. Only clicking on it reveals the relation. Thus, it'd be nice to have the TG-icon added to indicte that the given handle is for Telegram. Merci!

### Describe the solution you'd like to see implemented

See above. Icon works.

### How would this feature improve the Critter System for Eurofurence volunteers or attendees?

Makes it obvious that the given handle is for TG.

### Describe any alternatives you've considered or tried

... or write add "Telegram contact"... but hoooomans are visual beings. So... :)

**Comment by Corborax** [comment]
https://fontawesome.com/icons/telegram?f=brands&s=solid will do
