### ISSUE TITLE
Communicate Nickname restrictions better

### ISSUE THREAD

**Issue by KiraResari** [eurofurence/crittersystem#31]
### Is your feature request related to a specific event or situation at Eurofurence?

No

### What problem are you trying to solve with this feature?

I tried entering my nickname as "Kira Resari" because the "Nick" field did not communicate any restrictions. Then I got an error saying "Please enter a valid nick:Use up to 24 letters, numbers or connecting punctuations (.-_) for your nickname." While I do understand that this implies that spaces are not allowed, it would be better if the field clearly communicated this.

### Describe the solution you'd like to see implemented

Ideally, the field would have a real-time validator that checks the entered nickname and if an invalid character is entered communicates this specifically, like "Invalid character: '%'" or "Spaces are not allowed.

A more pragmatic solution would be to add this either as a tooltip, or in the field description:
"Nick (numbers, letters, and . _ - no spaces allowed)"

### How would this feature improve the Critter System for Eurofurence volunteers or attendees?

Usability & accessability

**Comment by RustyBraze** [comment]
To be looked

**Comment by RustyBraze** [comment]
> 2. Or we just keep the notification in place and just add the tooltip / info on the page, that spaces are not allowed.

This would be the best option. Automatic conversion usually cause unwanted results

**Comment by Corborax** [comment]
Was revolved with https://github.com/eurofurence/crittersystem/pull/53
