### ISSUE TITLE
Additional Location (Awareness & Inclusion)

### ISSUE THREAD

**Issue by Mstrlein** [eurofurence/crittersystem#38]
### What problem are you trying to solve with this feature?

Better overview for our Department (Awareness & Inlcusion), we show our presence at the CCH in general.
As we are not only only at the "Entrance Hall", it would be good to include the "CCH" to the locations.

### Describe the solution you'd like to see implemented

Please just ad "CCH" to the Locations.

### How would this feature improve the Critter System for Eurofurence volunteers or attendees?

It's just a better overview for our Department

### Describe any alternatives you've considered or tried

Just used "Entrance Hall" as Location for the whole CCH as Location.

**Comment by RustyBraze** [comment]
Just a ping about this @Corborax

**Comment by Corborax** [comment]
Talking with the team about this request. Adding a "CCH" location may cause confusion for volunteers.
